In [1]:
from sklearn.datasets import load_iris
iris_data = load_iris()

print iris_data.DESCR

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

X_data = StandardScaler().fit_transform(iris_data.data)
Y_data = OneHotEncoder(sparse=False).fit_transform(iris_data.target.reshape(-1, 1))

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_data, Y_data, test_size=0.3, random_state=0)

print X_train, Y_train
print X_test, Y_test

[[-1.02184904e+00 -2.43394714e+00 -1.46640561e-01 -2.62386821e-01]
 [ 7.95669016e-01 -1.31979479e-01  9.90107977e-01  7.90670654e-01]
 [ 1.03800476e+00  5.58610819e-01  1.10378283e+00  1.71209594e+00]
 [ 1.89829664e-01 -1.97355361e+00  7.05920842e-01  3.95774101e-01]
 [ 1.03800476e+00 -1.28296331e+00  1.16062026e+00  7.90670654e-01]
 [-2.94841818e-01 -1.28296331e+00  8.07091462e-02 -1.30754636e-01]
 [ 2.24968346e+00 -1.31979479e-01  1.33113254e+00  1.44883158e+00]
 [ 5.53333275e-01  5.58610819e-01  5.35408562e-01  5.27406285e-01]
 [-4.16009689e-01 -1.51316008e+00  2.38717193e-02 -1.30754636e-01]
 [ 5.53333275e-01 -8.22569778e-01  6.49083415e-01  7.90670654e-01]
 [ 5.53333275e-01 -5.92373012e-01  7.62758269e-01  3.95774101e-01]
 [-1.14301691e+00 -1.28296331e+00  4.21733708e-01  6.59038469e-01]
 [ 5.53333275e-01 -1.28296331e+00  7.05920842e-01  9.22302838e-01]
 [ 1.40150837e+00  3.28414053e-01  5.35408562e-01  2.64141916e-01]
 [ 7.95669016e-01 -1.31979479e-01  8.19595696e-01  1.05393502e

/Users/kongfanyang/anaconda2/lib/python2.7/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [3]:
import tensorflow as tf

x = tf.placeholder('float', [None, 4])
y = tf.placeholder('float', [None, 3])

w = tf.get_variable(
    name='w_weight', 
    shape=(4, 3), 
    initializer=tf.random_normal_initializer(stddev=0.1),
    regularizer=tf.contrib.layers.l2_regularizer(0.1)
)

b = tf.get_variable(
    name='b_weight', 
    shape=(1, 3), 
    initializer=tf.random_normal_initializer(stddev=0.1),
    regularizer=tf.contrib.layers.l2_regularizer(0.1)
)

logits = tf.matmul(x, w) + b
pred = tf.nn.softmax(logits)

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=y, logits=pred))
optimizer = tf.train.AdamOptimizer(learning_rate=0.1)
train_op = optimizer.minimize(cost)

In [10]:
from sklearn.utils import shuffle

init_global = tf.global_variables_initializer()
init_table = tf.tables_initializer()
init_local = tf.local_variables_initializer()

sess = tf.Session()
sess.run([init_global, init_table, init_local])

for i in range(80):
    loss = 0.0
    
    _, train_pred, train_loss = sess.run(
        [train_op, pred, cost],
        feed_dict={x: X_train, y: Y_train}
    )
    
    test_pred, test_loss = sess.run(
        [pred, cost],
        feed_dict={x: X_test, y: Y_test}
    )
    
    print("Epoch: %d, Train Logloss: %f, Test Logloss: %f" % (i, train_loss, test_loss))

Epoch: 0, Train Logloss: 1.096661, Test Logloss: 1.020735
Epoch: 1, Train Logloss: 1.000636, Test Logloss: 0.944961
Epoch: 2, Train Logloss: 0.915461, Test Logloss: 0.892208
Epoch: 3, Train Logloss: 0.856395, Test Logloss: 0.863461
Epoch: 4, Train Logloss: 0.820696, Test Logloss: 0.844433
Epoch: 5, Train Logloss: 0.797577, Test Logloss: 0.828279
Epoch: 6, Train Logloss: 0.780364, Test Logloss: 0.813165
Epoch: 7, Train Logloss: 0.766408, Test Logloss: 0.798806
Epoch: 8, Train Logloss: 0.754768, Test Logloss: 0.785236
Epoch: 9, Train Logloss: 0.745030, Test Logloss: 0.772501
Epoch: 10, Train Logloss: 0.736921, Test Logloss: 0.760638
Epoch: 11, Train Logloss: 0.730195, Test Logloss: 0.749689
Epoch: 12, Train Logloss: 0.724587, Test Logloss: 0.739687
Epoch: 13, Train Logloss: 0.719805, Test Logloss: 0.730644
Epoch: 14, Train Logloss: 0.715558, Test Logloss: 0.722539
Epoch: 15, Train Logloss: 0.711588, Test Logloss: 0.715320
Epoch: 16, Train Logloss: 0.707696, Test Logloss: 0.708913
Epoch: 

In [24]:
test_pred, test_loss = sess.run(
    [pred, cost],
    feed_dict={x: X_test, y: Y_test}
)

def max_encode(items):
    max_value = -9999.9
    max_code = -1
    for i in range(len(items)):
        if items[i] > max_value:
            max_code = i
    return max_code

def accuracy(y_test, y_true):
    acc_cnt = 0
    for i in range(len(y_test)):
        print y_test[i], y_true[i], max_encode(y_test[i]), max_encode(y_true[i])
        if max_encode(y_test[i]) == max_encode(y_true[i]):
            acc_cnt += 1
            
    return 1.0 * acc_cnt / len(y_test)
        
acc_rate = accuracy(test_pred, Y_test)
print "Accuracy Rate: %f" % acc_rate

[3.2777832e-06 1.1838914e-03 9.9881279e-01] [0. 0. 1.] 2 2
[3.117165e-05 9.933217e-01 6.647172e-03] [0. 1. 0.] 2 2
[9.9976879e-01 2.3122343e-04 4.5767670e-13] [1. 0. 0.] 2 2
[8.5944354e-09 3.3627782e-02 9.6637225e-01] [0. 0. 1.] 2 2
[9.965918e-01 3.408233e-03 5.803323e-11] [1. 0. 0.] 2 2
[6.5956760e-07 3.6700122e-04 9.9963236e-01] [0. 0. 1.] 2 2
[9.9867862e-01 1.3212991e-03 2.6758420e-11] [1. 0. 0.] 2 2
[1.330360e-04 8.907559e-01 1.091111e-01] [0. 1. 0.] 2 2
[8.82554832e-06 8.91763866e-01 1.08227246e-01] [0. 1. 0.] 2 2
[0.00111622 0.98110306 0.01778072] [0. 1. 0.] 2 2
[2.0836236e-05 4.3423387e-01 5.6574529e-01] [0. 0. 1.] 2 2
[0.00177039 0.92373365 0.07449599] [0. 1. 0.] 2 2
[4.6048727e-04 9.6806449e-01 3.1475008e-02] [0. 1. 0.] 2 2
[5.6505920e-05 8.2500744e-01 1.7493597e-01] [0. 1. 0.] 2 2
[0.00090772 0.8899414  0.10915091] [0. 1. 0.] 2 2
[9.9951434e-01 4.8569002e-04 2.2127148e-12] [1. 0. 0.] 2 2
[0.00196882 0.83832794 0.15970324] [0. 1. 0.] 2 2
[0.00464792 0.9577134  0.03763869] [0. 